prompt --application/deployment/definition
begin
--   Manifest
--     INSTALL: 445
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.04.15'
,p_release=>'21.1.6'
,p_default_workspace_id=>9510583246779566
,p_default_application_id=>111
,p_default_id_offset=>349023258543091759
,p_default_owner=>'SURVEY_TOOL'
);
wwv_flow_api.create_install(
 p_id=>wwv_flow_api.id(215415256849636528)
,p_deinstall_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'PROMPT >> Packages',
'drop package email_pkg;',
'drop package excel_gen;',
'drop package file_import;',
'drop package master_api;',
'drop package p00025_api;',
'drop package p00027_api;',
'drop package p00028_api;',
'drop package p00030_api;',
'drop package p00031_api;',
'drop package p00032_api;',
'drop package p00041_api;',
'drop package p00051_api;',
'drop package p00060_api;',
'drop package p00085_api;',
'drop package p00090_api;',
'drop package validation_api;',
'drop package xlsx_builder_pkg;',
'drop package zip_util_pkg;',
'',
'PROMPT >> Views',
'drop view p00020_vw;',
'drop view p00030_vw;',
'drop view p00042_vw;',
'drop view p00051_vw;',
'drop view p00060_vw;',
'drop view p01002_vw;',
'drop view p01003_vw;',
'drop view p01004_vw;',
'drop view p01005_vw;',
'drop view p01006_vw;',
'drop view p01007_vw;',
'drop view p01008_vw;',
'drop view p01009_vw;',
'drop view p01010_vw;',
'drop view p01011_vw;',
'drop view p01012_vw;',
'drop view p01013_vw;',
'drop view p01014_vw;',
'drop view p01015_vw;',
'',
'PROMPT >> Tables',
'drop table template_import_data;',
'drop table template_import_status;',
'drop table template_header_validations;',
'drop table template_header_group;',
'drop table template_header;',
'drop table template_automations;',
'drop table r_templates;',
'drop table r_dropdowns;',
'drop table r_header;',
'drop table r_person;',
'drop table r_shippingstatus;',
'drop table r_status;',
'drop table r_validation;',
'drop table r_spreadsheet_protection;',
'drop table files;',
'drop table import_errors;',
'',
'PROMPT >> SEQUENCES',
'DROP SEQUENCE dds_seq;',
'DROP SEQUENCE fil_seq;',
'DROP SEQUENCE hea_seq;',
'DROP SEQUENCE ier_seq;',
'DROP SEQUENCE per_seq;',
'DROP SEQUENCE sps_seq;',
'DROP SEQUENCE ssp_seq;',
'DROP SEQUENCE sts_seq;',
'DROP SEQUENCE thg_seq;',
'DROP SEQUENCE thv_seq;',
'DROP SEQUENCE tid_seq;',
'DROP SEQUENCE tid_row_seq;',
'DROP SEQUENCE tis_seq;',
'DROP SEQUENCE tpa_seq;',
'DROP SEQUENCE tph_seq;',
'DROP SEQUENCE tpl_seq;',
'DROP SEQUENCE val_seq;',
'',
'PROMPT >> LOGGER',
'drop package logger;',
'drop procedure logger_configure;',
'drop table logger_logs_apex_items cascade constraints;',
'drop table logger_prefs cascade constraints;',
'drop table logger_logs cascade constraints;',
'drop table logger_prefs_by_client_id cascade constraints;',
'drop sequence logger_logs_seq;',
'drop sequence logger_apx_items_seq;',
'',
'begin',
'	dbms_scheduler.drop_job(''LOGGER_PURGE_JOB'');',
'end;',
'/',
'',
'begin',
'	dbms_scheduler.drop_job(''LOGGER_UNSET_PREFS_BY_CLIENT'');',
'end;',
'/',
'',
'drop view logger_logs_5_min;',
'drop view logger_logs_60_min;',
'drop view logger_logs_terse;'))
);
wwv_flow_api.component_end;
end;
/
